### ISSUE TITLE
Mobile client

### ISSUE THREAD

**Issue by kanghyonkyong623** [whoGloo/loopback-jwt#11]
Is there any mobile client that use this lib?

**Comment by jmls** [comment]
Hi - this is a server-side lib for use with strongloop / loopback. On the client side, we use https://github.com/auth0/angular2-jwt

**Comment by kanghyonkyong623** [comment]
Is there any swift or android library or example?

**Comment by jmls** [comment]
a quick google does indeed show that there are many android and swift jwt libraries ;)

**Comment by kanghyonkyong623** [comment]
I am a beginner in the jwt and loopback, so I would like to get some help for this. 
Would you like to provide any example that communicate with your server library?
