### ISSUE TITLE
[QUERY] - usage

### ISSUE THREAD

**Issue by ketansp** [whoGloo/loopback-jwt#3]
Is there any sample code or documentation where I can understand the usage of this library? In my loopback project, I have OMSUser and Role models which are NOT extending the User and Role models respectively. I am using nJwt for auth. But the issue is, acls do not work with this kind of setup. I was wondering if this library could solve that?

**Comment by jmls** [comment]
this library links the strongloop user system with the credentials set in the jwt - you can use whatever model you want for the user by passing it in as an option. Also checkout the "beforeCreate" option on setup. Once the jwt has been authorised, then strongloop uses that "user" as the basis for it's security - so acl's etc should work as is

**Comment by ketansp** [comment]
Ok, thanks.
