### ISSUE TITLE
[QUERY] Login User

### ISSUE THREAD

**Issue by dgaletto** [whoGloo/loopback-jwt#4]
Hello! First of all, congratulations for the library.
How can I config the library to login or create an user without token?

Thanks!

**Comment by jmls** [comment]
thanks for the kinds words. To answer your question, this library is only for use when you *have* a token. You can use any jwt library - auth0 (https://auth0.com/) or stormpath (https://stormpath.com/) are two such services.

We use auth0 for authentication, which adds a `Authentication: Bearer <token>` to each http request. We needed to be able to link loopback users to this token scheme, hence we wrote this library

**Comment by dgaletto** [comment]
Thanks for your answer!
