### ISSUE TITLE
1.0.2 not available in npm

### ISSUE THREAD

**Issue by mpycio** [whoGloo/loopback-jwt#6]
https://www.npmjs.com/package/loopback-jwt

julianls published a year ago
1.0.1 is the latest release

Can 1.0.2 be made available as npm package?

**Comment by jmls** [comment]
oops, sorry. I will try and make it available tonight.

**Comment by jmls** [comment]
should be there now.

**Comment by mpycio** [comment]
great, all works now

Thanks
